// src/bootcamp_chat_frontend/src/App.vue
<script lang="ts">
import { ref } from 'vue';
import { bootcamp_chat_backend, canisterId, createActor } from '../../declarations/bootcamp_chat_backend';
import { AuthClient } from '@dfinity/auth-client';
import { HttpAgent } from '@dfinity/agent';
import type { Identity } from '@dfinity/agent';
import { Principal } from '@dfinity/principal';
import type { UserData } from '../../declarations/bootcamp_chat_backend/bootcamp_chat_backend.did';

export const IDENTITY_PROVIDER = import.meta.env.VITE_IDENTITY_PROVIDER;

export default {
  data() {
    return {
      newChat: "",
      chats: [] as string[][],
      identity: undefined as undefined | Identity,
      principal: undefined as undefined | Principal,
      targetPrincipal: "",
      userData: undefined as undefined | UserData,
      newUsername: "",
      allUsers: [] as [Principal, UserData][],
      balance: null,
      amountToSend: 0,
      transferDelay: 0
    }
  },
  methods: {
    isUserLogged() {
      if (!this.identity || !this.principal || this.principal === Principal.anonymous()) {
        throw new Error("PLZ log in")
      }
      return {
        identity: this.identity,
        principal: this.principal
      }
    },
    validateTargetPrincipal() {
      const cleanTargetPrincipal = this.targetPrincipal.trim();
      if (cleanTargetPrincipal === "") {
        throw new Error("No principal")
      }
      const targetPrincipal = Principal.fromText(cleanTargetPrincipal)
      if (!targetPrincipal || targetPrincipal === Principal.anonymous()) {
        throw new Error("Wrong target")
      }
      return targetPrincipal
    },
    getAuthClient() {
      this.isUserLogged()
      return createActor(canisterId, {
        agentOptions: {
          identity: this.identity
        }
      });
    },
    async dodajChatMSG() {
      console.log("Entering dodajChatMSG")

      const targetPrincipal = this.validateTargetPrincipal()
      console.log("Target principal", targetPrincipal)

      const backend = this.getAuthClient();
      console.log("Backend", backend)

      console.log("Before Added chat msg")
      await backend.add_chat_msg(this.newChat, targetPrincipal)
      console.log("After Added chat msg")

      console.log("Before pobierzChaty")
      await this.pobierzChaty()
      console.log("After pobierzChaty")
    },
    async pobierzChaty() {
      const { identity, principal } = this.isUserLogged()
      const targetPrincipal = this.validateTargetPrincipal()

      const chatPath = [targetPrincipal, identity.getPrincipal()].sort()
      console.log("IN pobierzChaty Chat path", chatPath)
      console.log("IN pobierzChaty Chat path str", chatPath.toLocaleString())
      const chats = await bootcamp_chat_backend.get_chat(chatPath)
      console.log("IN pobierzChaty Chats", chats)
      console.log("IN pobierzChaty Chats", chats.toLocaleString())

      this.chats = chats
    },
    async registerUsername() {
      const trimedUsername = this.newUsername.trim();
      const backend = this.getAuthClient();
      await backend.register(trimedUsername)
      await this.getUserData()
      await this.getAllUsers()
    },
    async getUserData() {
      const { principal } = this.isUserLogged()
      const maybeUserData = await bootcamp_chat_backend.get_user(principal as Principal)
      if (maybeUserData.length === 0) {
        this.userData = undefined
      } else {
        this.userData = maybeUserData[0]
      }
      await this.fetchBalance()
      console.log("User data", this.userData)
    },
    async getAllUsers() {
      this.allUsers = await bootcamp_chat_backend.get_users()
    },
    async transfer() {
      const { principal } = this.isUserLogged()
      const backend = this.getAuthClient();

      const targetPrincipal = this.validateTargetPrincipal()
      let to_principal = targetPrincipal


      //let to_principal = Principal.fromText('agt74-uhoi3-3eolc-fwiby-qcr6q-b2w7a-gcy7v-t3bpi-rpie2-6yqai-aae');

      //. todo validate amount to send


      console.log("Before transfer from", principal, "to", to_principal, "amount", this.amountToSend, "delay", this.transferDelay)

      let acc = { owner: to_principal, subaccount: [] };

      let transferArgs = {
        to_account: acc,
        amount: this.amountToSend
      };


      // the fun ction below returns:
      // type Result = variant { Ok : nat; Err : text };
      let result = await backend.transfer(transferArgs);
      console.log(result);

    },

    async logout() {
      const authClient = await AuthClient.create();
      await authClient.logout()
      this.identity = undefined;
      this.principal = undefined;
      this.chats = [];
      this.userData = undefined
      localStorage.clear()
    },



    async login() {
      const authClient = await AuthClient.create();
      await authClient.login({
        identityProvider: IDENTITY_PROVIDER,
        onSuccess: async () => {
          await this.handleAuthentication(authClient);
        }
      });
    },

    // helpers
    async handleAuthentication(authClient: AuthClient) {
      const identity = authClient.getIdentity();
      const principal = identity.getPrincipal();
      this.principal = principal;
      this.identity = identity;
      console.log("Zalogowano", this.principal);
      await this.getUserData();
      await this.getAllUsers();
    },
    async fetchBalance() {
      const { principal } = this.isUserLogged()
      const backend = this.getAuthClient();
      let result = await backend.get_balance()
      if (result.Ok !== undefined) {
        this.balance = result.Ok;
      } else {
        this.balance = null;
      }
      console.log(result)
    },

  },
  async mounted() {
    console.log('Entering mounted');
    const authClient = await AuthClient.create();
    const isAuthenticated = await authClient.isAuthenticated();
    console.log('Is authenticated', isAuthenticated);
    if (isAuthenticated) {
      await this.handleAuthentication(authClient);
    }
  },

}
</script>

<template>
  <main>
    <button v-if="!principal" @click="login">login</button>
    <button v-if="principal" @click="logout">logout</button>

    <div v-if="principal && !userData">
      <input v-model="newUsername" placeholder="nick" /> <button @click="registerUsername">register</button>
    </div>
    <div v-if="principal && userData">
      <p>Nick: {{ userData.nickname }}</p>
      <p>Principal: {{ principal }}</p>
      <p>Balance: {{ balance }}</p>

      <div v-if="allUsers">
        <select v-model="targetPrincipal" @change="pobierzChaty">
          <option disabled value="">Please select one</option>
          <option v-for="[userPrincipal, userData] in allUsers" :value="userPrincipal.toText()">{{ userData.nickname }}
          </option>
        </select>
      </div>
      <div>
        <div v-for="chat in chats[0]">
          {{ chat }}
        </div>
      </div>
      <div>
        <textarea v-model="newChat" placeholder="wiadomosc"></textarea><button @click="dodajChatMSG">Dodaj
          notatke</button>
      </div>
      <label for="amountToSend">Amount to send:</label>
      <input v-model="amountToSend" type="number" placeholder="Amount to send" />

      <label for="transferDelay">Delay in seconds:</label>
      <input v-model="transferDelay" type="number" placeholder="Delay in seconds" />
      <button @click="transfer">Direct transfer</button>
    </div>
  </main>
</template>

// src/icp_will_frontend/src/App.tsx
import React, { useState, useEffect } from 'react';
import { AuthClient } from '@dfinity/auth-client';
import { HttpAgent, Identity } from '@dfinity/agent';
import { Principal } from '@dfinity/principal';
import { icp_will_backend, canisterId, createActor } from '../../declarations/icp_will_backend';
import type { TransferArgs, UserData } from '../../declarations/icp_will_backend/icp_will_backend.did';
import { Button } from './components/ui/button';
import { Textarea } from './components/ui/textarea';
import { Label } from './components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './components/ui/select';
import { Input } from './components/ui/input';
import { Card } from './components/ui/card';
import Layout from './components/ui/layout';

const IDENTITY_PROVIDER = import.meta.env.VITE_IDENTITY_PROVIDER;

interface Beneficiary {
  nickname: string;
  icpAmount: number;
  userPrincipal: Principal;
}

const App: React.FC = () => {
  const [newChat, setNewChat] = useState<string>("");
  const [chats, setChats] = useState<string[][]>([]);
  const [identity, setIdentity] = useState<Identity | undefined>();
  const [principal, setPrincipal] = useState<Principal | undefined>();
  const [targetPrincipal, setTargetPrincipal] = useState<string>("");
  const [userData, setUserData] = useState<UserData | undefined>();
  const [newUsername, setNewUsername] = useState<string>("");
  const [allUsers, setAllUsers] = useState<[Principal, UserData][]>([]);
  const [balance, setBalance] = useState<BigInt | null>(null);
  const [amountToSend, setAmountToSend] = useState<number>(0);
  const [transferDelay, setTransferDelay] = useState<number>(0);
  const [beneficiaries, setBeneficiaries] = useState<Beneficiary[]>([]);
  const [executionAfterYears, setExecutionAfterYears] = useState<number>(0);
  const [executionAfterMonths, setExecutionAfterMonths] = useState<number>(0);
  const [executionAfterSeconds, setExecutionAfterSeconds] = useState<number>(0);

  const isBeneficiaryValid = targetPrincipal && targetPrincipal !== principal?.toText() && targetPrincipal !== "Please select one";
  const isSaveAndActivateEnabled = beneficiaries.length > 0 && (executionAfterYears > 0 || executionAfterMonths > 0 || executionAfterSeconds > 0);

  const isUserLogged = () => {
    if (!identity || !principal || principal.isAnonymous()) {
      throw new Error("PLZ log in");
    }
    return { identity, principal };
  };

  const validateTargetPrincipal = () => {
    const cleanTargetPrincipal = targetPrincipal.trim();
    if (cleanTargetPrincipal === "") {
      throw new Error("No principal");
    }
    const target = Principal.fromText(cleanTargetPrincipal);
    if (!target || target.isAnonymous()) {
      throw new Error("Wrong target");
    }
    return target;
  };

  const getAuthClient = () => {
    isUserLogged();
    return createActor(canisterId, {
      agentOptions: {
        identity: identity
      }
    });
  };

  const dodajChatMSG = async () => {
    const target = validateTargetPrincipal();
    const backend = getAuthClient();
    await backend.add_chat_msg(newChat, target);
    await pobierzChaty();
  };

  const pobierzChaty = async () => {
    const { identity, principal } = isUserLogged();
    const target = validateTargetPrincipal();
    const chatPath = [target, identity.getPrincipal()].sort();
    const fetchedChats = await icp_will_backend.get_chat(chatPath);
    setChats(fetchedChats);
  };

  const registerUsername = async () => {
    const trimedUsername = newUsername.trim();
    const backend = getAuthClient();
    await backend.register(trimedUsername);
    await getUserData();
    await getAllUsers();
  };

  const getUserData = async () => {
    const { principal } = isUserLogged();
    const maybeUserData = await icp_will_backend.get_user(principal);
    setUserData(maybeUserData.length === 0 ? undefined : maybeUserData[0]);
    await fetchBalance();
  };

  const getAllUsers = async () => {
    const users = await icp_will_backend.get_users();
    setAllUsers(users);
  };

  const transfer = async () => {
    const { principal } = isUserLogged();
    const backend = getAuthClient();
    const target = validateTargetPrincipal();

    const transferArgs: TransferArgs = {
      to_account: {
        owner: target,
        subaccount: [] // This should be compatible with the expected type
      },
      amount: BigInt(amountToSend) // Convert to BigInt if the backend expects it
    };

    let result = await backend.transfer(transferArgs);
    console.log(result);
  };

  const logout = async () => {
    const authClient = await AuthClient.create();
    await authClient.logout();
    setIdentity(undefined);
    setPrincipal(undefined);
    setChats([]);
    setUserData(undefined);
    localStorage.clear();
  };

  const login = async () => {
    const authClient = await AuthClient.create();
    await authClient.login({
      identityProvider: IDENTITY_PROVIDER,
      onSuccess: async () => {
        await handleAuthentication(authClient);
      }
    });
  };

  const addBeneficiary = () => {
    if (isBeneficiaryValid) {
      const selectedUser = allUsers.find(
        ([userPrincipal]) => userPrincipal.toText() === targetPrincipal
      );
      if (selectedUser) {
        setBeneficiaries([...beneficiaries, {
          nickname: selectedUser[1].nickname,
          icpAmount: 0,
          userPrincipal: selectedUser[0],
        }]);
      }
    }
  };

  const removeBeneficiary = (index: number) => {
    setBeneficiaries(beneficiaries.filter((_, i) => i !== index));
  };

  const saveAndActivate = () => {
    if (isSaveAndActivateEnabled) {
      const executionTime = {
        years: executionAfterYears,
        months: executionAfterMonths,
        seconds: executionAfterSeconds,
      };
      const payload = {
        beneficiaries: beneficiaries.map(b => ({
          principal: b.userPrincipal.toText(),
          nickname: b.nickname,
          icpAmount: b.icpAmount,
        })),
        executionAfter: executionTime,
      };
      console.log('Save and Activate triggered with payload:', payload);
      // Add your activation logic here (API calls, etc.)
    }
  };

  const handleAuthentication = async (authClient: AuthClient) => {
    const identity = authClient.getIdentity();
    const principal = identity.getPrincipal();
    setPrincipal(principal);
    setIdentity(identity);
    console.log("Zalogowano", principal);
    await getUserData();
    await getAllUsers();
  };

  const fetchBalance = async () => {
    const { principal } = isUserLogged();
    const backend = getAuthClient();
    let result = await backend.get_balance();
    if ('Ok' in result) {
      setBalance(result.Ok);
    } else {
      setBalance(null);
    }
    console.log(result);
  };

  useEffect(() => {
    const init = async () => {
      const authClient = await AuthClient.create();
      const isAuthenticated = await authClient.isAuthenticated();
      console.log('Is authenticated', isAuthenticated);
      if (isAuthenticated) {
        await handleAuthentication(authClient);
      }
    };
    init();
  }, []);

  return (
    <Layout navItems={[!principal ? (
      <Button onClick={login}>login</Button>
    ) : (
      <Button onClick={logout}>logout</Button>
    )]}>
 <>

      {principal && !userData && (
        <Card className='flex flex-col gap-6 py-4 px-8'>
          <Input
            value={newUsername}
            onChange={(e) => setNewUsername(e.target.value)}
            placeholder="nick"
          />
          <Button onClick={registerUsername}>register</Button>
        </Card>
      )}

      {principal && userData && (
        <Card className='flex flex-col gap-6 py-4 px-8'>
          <p>Nick: {userData.nickname}</p>
          <p>Principal: {principal.toString()}</p>
          <p>Balance: {Number(balance)}</p>

          {allUsers && (
            <Select onValueChange={(value) => { setTargetPrincipal(value); pobierzChaty(); }}>
                <SelectTrigger>
                  <SelectValue placeholder="Please select one" />
                </SelectTrigger>
                <SelectContent>
                  {allUsers.map(([userPrincipal, userData]) => (
                    <SelectItem key={userPrincipal.toText()} value={userPrincipal.toText()}>
                      {userData.nickname}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
          )}

          <Card>
            {chats[0]?.map((chat, index) => (
              <div key={index}>{chat}</div>
            ))}
          </Card>


            <Textarea
              value={newChat}
              onChange={(e) => setNewChat(e.target.value)}
              placeholder="wiadomosc"
            />
            <Button onClick={dodajChatMSG}>Dodaj notatke</Button>


          <Label htmlFor="amountToSend">Amount to send:</Label>
          <Input
            value={amountToSend}
            onChange={(e) => setAmountToSend(Number(e.target.value))}
            type="number"
            placeholder="Amount to send"
          />

          <Label htmlFor="transferDelay">Delay in seconds:</Label>
          <Input
            value={transferDelay}
            onChange={(e) => setTransferDelay(Number(e.target.value))}
            type="number"
            placeholder="Delay in seconds"
          />
          <Button onClick={transfer}>Direct transfer</Button>
          <Button onClick={addBeneficiary} disabled={!isBeneficiaryValid}>Add beneficiary</Button>


          {beneficiaries.map((beneficiary, index) => (
            <Card key={index} style={{ marginTop: '10px' }}>
              <Input value={beneficiary.nickname} readOnly />
              <Input
                value={beneficiary.icpAmount}
                onChange={(e) => {
                  const newBeneficiaries = [...beneficiaries];
                  newBeneficiaries[index].icpAmount = Number(e.target.value);
                  setBeneficiaries(newBeneficiaries);
                }}
                type="number"
                placeholder="ICP value"
              />
              <Button onClick={() => removeBeneficiary(index)}>Remove</Button>
            </Card>
          ))}

          {beneficiaries.length > 0 && (
            <Card style={{ marginTop: '20px' }}>
              <Label>Execution after:</Label>
              <Input
                value={executionAfterYears}
                onChange={(e) => setExecutionAfterYears(Number(e.target.value))}
                type="number"
                min="0"
                placeholder="Years"
              />
              <Input
                value={executionAfterMonths}
                onChange={(e) => setExecutionAfterMonths(Number(e.target.value))}
                type="number"
                min="0"
                placeholder="Months"
              />
              <Input
                value={executionAfterSeconds}
                onChange={(e) => setExecutionAfterSeconds(Number(e.target.value))}
                type="number"
                min="0"
                placeholder="Seconds"
              />
            </Card>
          )}

          <Card style={{ marginTop: '20px' }}>
            <Button onClick={saveAndActivate} disabled={!isSaveAndActivateEnabled}>Save and Activate</Button>
          </Card>
        </Card>
      )}
      </>
      </Layout>
  );
};

export default App;
